name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.1-linux-fedora-27-netcoreapp2.1
      with:
        args: --help
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Package dependencies
      run: |
        python -m pip install --upgrade pip
        cd hello_world
        pip download -r requirements.txt
        unzip \*.whl
        rm *.whl
        ls -la
    - name: Pack Application
      uses: docker://octopusdeploy/octo:latest
      with:
        args: pack . --basePath hello_world --id AwsSamLambda --version 1.0.0.0 --format zip
    - name: Push to Octopus
      uses: docker://octopusdeploy/octo:latest
      with:
        args: push --server ${{ secrets.MATTC_URL }} --apiKey ${{ secrets.MATTC_API_KEY }} --package AwsSamLambda.1.0.0.0.zip --overwrite-mode IgnoreIfExists
