name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Version
      uses: docker://gittools/5.0.2-beta1-4-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/version.txt\""
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Package dependencies
      run: |
        python -m pip install --upgrade pip
        cd hello_world
        pip download -r requirements.txt
        unzip \*.whl
        rm *.whl
        ls -la
    - name: Pack Application
      uses: docker://octopusdeploy/octo:latest
      with:
        args: pack . --basePath hello_world --id AwsSamLambda --version $(cat /github/workspace/version.txt) --format zip
    - name: Push to Octopus
      uses: docker://octopusdeploy/octo:latest
      with:
        args: push --server ${{ secrets.MATTC_URL }} --apiKey ${{ secrets.MATTC_API_KEY }} --package AwsSamLambda.$(cat /github/workspace/version.txt).zip --overwrite-mode IgnoreIfExists
